site_name: Nasena 21
theme:
  name: material
  language: id
  font:
    text: Noto Sans Japanese
    code: Noto Serif Japanese

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue 
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


  logo: kobo.jpg

  favicon: kobo.jpg

  plugins:  
    - mkdocs-video
    - kroki:
      ServerURL: !ENV [KROKI_SERVER_URL, 'https://kroki.io']
      FileTypes:
        - png
        - svg
      FileTypeOverrides:
        mermaid: png
      FailFast: !ENV CI

  features:
    - tabs
    - instant
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    # - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlighting
    - search.share
    - meta
    - admonition
    - attr_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.superfences


extra_css:
  - stylesheets/extra.css

nav:
  - Home: 'index.md'
  - Guides:
    - 'Pendahuluan': 'pendahuluan.md'
    - 'Main Guide': 'main_guide.md'
    - 'Kanji': 'kanji.md'  
    - 'Speaking': 'speaking.md'
  - Setup:  
    - Main:
      - 'Anki': 'anki.md'
      - 'Yomitan': 'yomitan.md'
      - 'ShareX' : 'sharex.md'
    - Visual Novel:
      - Visual Novel : visual_novel.md
    - Light Novel:
      - Light Novel: light_novel.md
    - Anime:
      - Anime: anime.md
    - Manga:
      - Manga: manga.md
  - Recommendations:
    - Recommendations: 'recommendations.md'
  - Resources:
    - Resources: resources.md
  - Grammar:
    - Grammar: grammar/grammar.md
    - Credit: cure-dolly/credit.md
    - 'Basic Sentence Structure and Core Grammar': 
      - 'cure-dolly\1_part_of_speech.md'
      - '2. The Invisible Carriage and The を Particle': 'cure-dolly/2-the-invisible-carriage-and-the-を-particle.md'
      - '3. The は Particle': 'cure-dolly/3-the-は-particle.md'
      - '4. Japanese Verb Tenses': 'cure-dolly/4-japanese-verb-tenses.md'
      - '5. Verb Groups and The て Form': 'cure-dolly/5-verb-groups-and-the-て-form.md'
      - '6. Adjectives': 'cure-dolly/6-adjectives.md'
      - '7. Negative Forms and Adjectives in Past Tense': 'cure-dolly/7-negative-forms-and-adjectives-in-past-tense.md'
      - '7.5. Conjugation': 'cure-dolly/7-5-conjugation.md'
      - '9. The に and へ Particles': 'cure-dolly/8-the-に-and-へ-particles.md'
      - '8b. Particles Explained': 'cure-dolly/8b-particles-explained.md'
      - '9. The Subject of The Japanese Sentence: Expressing Desire ほしい たい たがる': 'cure-dolly/9-the-subject-of-the-japanese-sentence-expressing-desire-ほしい-たい-たがる.md'
      - '10. Helper Verbs: The Potential Helper Verb': 'cure-dolly/10-helper-verbs-the-potential-helper-verb.md'
      - '11. Compound Sentences: くれる, あげる and More Uses of The て Form': 'cure-dolly/11-compound-sentences-くれる-あげる-and-more-uses-of-the-て-form.md'
      - '12. Quotation Particle と, Compound Verbs, Nouns': 'cure-dolly/12-quotation-particle-と-compound-verbs-nouns.md'
      - '13. Passive Conjugation: Receptive Helper Verb': 'cure-dolly/13-passive-conjugation-receptive-helper-verb.md'
      - '14. Adverbs and The も Particle': 'cure-dolly/14-adverbs-and-the-も-particle.md'
      - '15. Transitive Intransitive Verbs': 'cure-dolly/15-transitive-intransitive-verbs.md'
      - '16. てみる, や Particle, から Particle Exclusive and': 'cure-dolly/16-てみる-や-particle-から-particle-exclusive-and.md'
      - '17. Polite Japanese and The Volitional': 'cure-dolly/17-polite-japanese-and-the-volitional.md'
      - '18. って, は Mysteries Explained: おうとする, とする, として, という, っていう': 'cure-dolly/18-って-は-mysteries-explained-おうとする-とする-として-という-っていう.md'
      - '19. Causative, Causative Receptive': 'cure-dolly/19-causative-causative-receptive.md'
      - '20. Directionals: それ, その, そんな, そう, etc.': 'cure-dolly/20-directionals-それ-その-そんな-そう-etc.md'
    - 'Advanced Grammar and Expressions':
      - '21. てある, ている, ておく': 'cure-dolly/21-てある-ている-ておく.md'
      - '22. ては, ても': 'cure-dolly/22-ては-ても.md'
      - '23. だって, だから, それから': 'cure-dolly/23-だって-だから-それから.md'
      - '24. Hearsay, Guesses: そう, そうだ, そうです': 'cure-dolly/24-hearsay-guesses-そう-そうだ-そうです.md'
      - '25. らしい vs そうだ, そうです, っぽい (ppoi)': 'cure-dolly/25-らしい-vs-そうだ-そうです-っぽい-ppoi.md'
      - '26. Similes: ようだ, のように, のような, みたい': 'cure-dolly/26-similes-ようだ-のように-のような-みたい.md'
      - '27. ばかり': 'cure-dolly/27-ばかり.md'
      - '28. ように: One Key to All The Main Uses': 'cure-dolly/28-ように-one-key-to-all-the-main-uses.md'
      - '29. ことにする, ことになる': 'cure-dolly/29-ことにする-ことになる.md'
      - '30. Japanese Conditionals: と': 'cure-dolly/30-japanese-conditionals-と.md'
      - '31. The ば, れば Conditional': 'cure-dolly/31-the-ば-れば-conditional.md'
      - '32. The たら, なら Conditionals': 'cure-dolly/32-the-たら-なら-conditionals.md'
      - '33. Limiting Terms: だけ, しか, ばかり, のみ': 'cure-dolly/33-limiting-terms-だけ-しか-ばかり-のみ.md'
      - '34. Understand Any Sentence': 'cure-dolly/34-understand-any-sentence.md'
      - '35. より, のほう, 一方': 'cure-dolly/35-より-のほう-一方.md'
      - '36. 所: The Concept of Place': 'cure-dolly/36-所-the-concept-of-place.md'
      - '37. New Structure Secrets: な vs の, なる, たる Adjectives': 'cure-dolly/37-new-structure-secrets-な-vs-の-なる-たる-adjectives.md'
      - '38. When It Isn’t Means It Is: じゃない, ではない': 'cure-dolly/38-when-it-isn-t-means-it-is-じゃない-ではない.md'
      - '39. The か Particle: Buried Questions かな, もんか, かどうか': 'cure-dolly/39-the-か-particle-buried-questions-かな-もんか-かどうか.md'
      - '40. 3 Pitfalls in Japanese and How to Avoid Them': 'cure-dolly/40-3-pitfalls-in-japanese-and-how-to-avoid-them.md'
    - 'Language Learning Strategies and Sentence Analysis':
      - '41. 5 Key Facts About The Basic Structure of Japanese': 'cure-dolly/41-5-key-facts-about-the-basic-structure-of-japanese.md'
      - '42. Basic Word Confusion: まま': 'cure-dolly/42-basic-word-confusion-まま.md'
      - '43. Paradigm Shift: Cut Through The Confusion': 'cure-dolly/43-paradigm-shift-cut-through-the-confusion.md'
      - '44. How to Use Natural Japanese: ちゃう, ちゃった': 'cure-dolly/44-how-to-use-natural-japanese-ちゃう-ちゃった.md'
      - '45. First Step Guide into Self Immersion Technique': 'cure-dolly/45-first-step-guide-into-self-immersion-technique.md'
      - '46. Word Order Matters: 2 Simple Rules to Crack Tough Sentences': 'cure-dolly/46-word-order-matters-2-simple-rules-to-crack-tough-sentences.md'
      - '47. How to Understand Japanese: Your Secret Weapon for Breaking Down Sentences': 'cure-dolly/47-how-to-understand-japanese-your-secret-weapon-for-breaking-down-sentences.md'
      - '48. Dealing with Ambiguity in Japanese': 'cure-dolly/48-dealing-with-ambiguity-in-japanese.md'
      - '49. Japanese Point of View Deconfused: もらう, てもらう': 'cure-dolly/49-japanese-point-of-view-deconfused-もらう-てもらう.md'
      - '50. 2 Aspects of Japanese That Foreigners Can’t Fathom: させてもらう, Last Secret of the Potential': 'cure-dolly/50-2-aspects-of-japanese-that-foreigners-can-t-fathom-させてもらう-last-secret-of-the-potential.md'
      - '51. How to Read a Japanese 怪談 (かいだん) Ghost Story': 'cure-dolly/51-how-to-read-a-japanese-怪談-かいだん-ghost-story.md'
      - '52. In-Depth Japanese Sentence Analysis in Real Native Context': 'cure-dolly/52-in-depth-japanese-sentence-analysis-in-real-native-context.md'
      - '53. Enjoy Japanese Horror in Japanese': 'cure-dolly/53-enjoy-japanese-horror-in-japanese.md'
      - '54. Irregularities: How They Work: 見る, 見られる, 見れる, 見える, 聞く, 聞ける, 聞こえる': 'cure-dolly/54-irregularities-how-they-work-見る-見られる-見れる-見える-聞く-聞ける-聞こえる.md'
      - '55. Secrets of the で Particle: Why Do We Say みんなで行く and 世界で一番': 'cure-dolly/55-secrets-of-the-で-particle-why-do-we-say-みんなで行く-and-世界で一番.md'
      - '56. Agility: Deeper Secrets of は and の Particles': 'cure-dolly/56-agility-deeper-secrets-of-は-and-の-particles.md'
      - '57. 込む (komu) and the Secret of Multi-Meaning Japanese Words': 'cure-dolly/57-込む-komu-and-the-secret-of-multi-meaning-japanese-words.md'
      - '58. Japanese Double Particles: How They Work': 'cure-dolly/58-japanese-double-particles-how-they-work.md'
      - '59. Untranslatable Japanese Exists: How to Understand It': 'cure-dolly/59-untranslatable-japanese-exists-how-to-understand-it.md'
      - '60. The Other Half of Japanese Structure: Non-Logical Topic-Comment Structure': 'cure-dolly/60-the-other-half-of-japanese-structure-non-logical-topic-comment-structure.md'
    - 'Advanced Topics and Cultural Context':
      - '61. は and が: The Deeper Secrets, The Yin-Yang Structure of Japanese': 'cure-dolly/61-は-and-が-the-deeper-secrets-the-yin-yang-structure-of-japanese.md'
      - '62. ておく vs てしまう: Helper Verb Secrets': 'cure-dolly/62-ておく-vs-てしまう-helper-verb-secrets.md'
      - '63. Wild Sentence Enders in Real-Life Japanese: かい, だい, ぜ, ぞ, さ, から, し, ちょうだい': 'cure-dolly/63-wild-sentence-enders-in-real-life-japanese-かい-だい-ぜ-ぞ-さ-から-し-ちょうだい.md'
      - '64. Things Get Strange: もの and こと Advanced Secrets, ものだ, ことがある, こと as Sentence Ender': 'cure-dolly/64-things-get-strange-もの-and-こと-advanced-secrets-ものだ-ことがある-こと-as-sentence-ender.md'
      - '65. Coming and Going: Deeper Secrets of 行く and 来る, て行く and て来る (te-iku, te-kuru)': 'cure-dolly/65-coming-and-going-deeper-secrets-of-行く-and-来る-て行くand-て来る-te-iku-te-kuru.md'
      - '66. Hidden Subjects in Japanese and How to Understand Them': 'cure-dolly/66-hidden-subjects-in-japanese-and-how-to-understand-them.md'
      - '67. もう and まだ: The Time Relations That Make Sense of Them': 'cure-dolly/67-もう-and-まだ-the-time-relations-that-make-sense-of-them.md'
      - '68. Japanese Underlying Logic: わけ, そういうわけ, わけが分からない, わけない': 'cure-dolly/68-japanese-underlying-logic-わけ-そういうわけ-わけが分からない-わけない.md'
      - '69. Japanese in the Wild: Tackling Native Japanese Material (怪談) 4': 'cure-dolly/69-japanese-in-the-wild-tackling-native-japanese-material-怪談-4.md'
      - '70. かける and かかる: All-Purpose Japanese Explained': 'cure-dolly/70-かける-かかる-all-purpose-japanese-explained.md'
      - '71. Japanese Counters: 3 Simple Rules': 'cure-dolly/71-japanese-counters-3-simple-rules.md'
      - '72. The Great Connector: い-Stem Magic': 'cure-dolly/72-the-great-connector-い-stem-magic.md'
      - '73. Secrets of 気: 気になる, 気にする, 気がする, 気に入る, etc.': 'cure-dolly/73-secrets-of-気-気になる-気にする-気がする-気に入る-etc.md'
      - '74. Love and Other Mysteries of こと: あなたのことが好き, 私のことが嫌い, ということ, そういうこと, どういうこと, そんなこと': 'cure-dolly/74-love-and-other-mysteries-of-こと-あなたのことが好き-私のことが嫌い-ということ-そういうこと-どういうこと-そんなこと.md'
      - '75. Japanese is Not English: How Expression Strategies Differ, Polite (英本語) vs Rude Japanese': 'cure-dolly/75-japanese-is-not-english-how-expression-strategies-differ-polite-英本語-rude-japanese.md'
      - '76. The Right Opening: あく, あける, ひらく, ひらける, 開く, 開け': 'cure-dolly/76-the-right-opening-あく-あける-ひらく-ひらける-開く-開け.md'
      - '77. Real Japanese Structure vs Tae Kim: Structural Review of Tae Kim’s Japanese Grammar': 'cure-dolly/77-real-japanese-structure-vs-tae-kim-structural-review-of-tae-kim-s-japanese-grammar.md'
      - '78. Breaking the Core: Tae Kim vs The Copula, Japanese Structure-Based Critical Review': 'cure-dolly/78-breaking-the-core-tae-kim-vs-the-copula-japanese-structure-based-critical-review.md'
      - '79. Deeper Secret of the Copula': 'cure-dolly/79-deeper-secret-of-the-copula.md'
      - '80. Dropped Particles: Casual Omissions': 'cure-dolly/80-dropped-particles-casual-omissions.md'
      - '81. Global Principle of All Japanese Word Forms': 'cure-dolly/81-global-principle-of-all-japanese-word-forms.md'
      - '82. なんて, なんか, など: 3 Common Words Clarified': 'cure-dolly/82-なんて-なんか-など-3-common-words-clarified.md'
      - '83. Three Levels of Command in Japanese: て Form Commands, なさい, な - Commands, Imperative Form': 'cure-dolly/83-three-levels-of-command-in-japanese-て-form-commands-なさい-な-commands-imperative-form.md'
      - '84. である and the Structure of Japanese: What Older Copulas Tell Us - である, であります, でござる, でございます': 'cure-dolly/84-である-and-the-structure-of-japanese-what-older-copulas-tell-us-である-であります-でござる-でございます.md'
      - '85. まい: The Negative Helper': 'cure-dolly/85-まい-the-negative-helper.md'
      - '86. 次第 (shidai)': 'cure-dolly/86-次第-shidai.md'
      - '87. Japanese Structure Inverted: Strange Life of しか': 'cure-dolly/87-japanese-structure-inverted-strange-life-of-しか.md'
      - '88. xをしたい vs xがしたい': 'cure-dolly/88-xをしたい-vs-xがしたい.md'
      - '89. De-Mystifying Japanese: The Universal Subject': 'cure-dolly/89-de-mystifying-japanese-the-universal-subject.md'
      - '90. Japanese Punctuation: How It Works': 'cure-dolly/90-japanese-punctuation-how-it-works.md'
      - '91. Outer Limits: 限る, 限り, Its Many Meanings and How They Work: 知っている限り, とは限らない, and More': 'cure-dolly/91-outer-limits-限る-限り-its-many-meanings-and-how-they-work-知っている限り-とは限らない-and-more.md'
      - '92. Will English Eat Japanese? Loan Word Invasion: Is It Really a Threat?': 'cure-dolly/92-will-english-eat-japanese-loan-word-invasion-is-it-really-a-threat.md'
      - '93. Cussin’ Em Out with くせに: How It Works': 'cure-dolly/93-cussin-em-out-with-くせに-how-it-works.md'
      - '94. くらい vs ほど': 'cure-dolly/94-くらい-vs-ほど.md'
      - '95. Using Word History the Smart Way: どうも, やっぱり, やはり': 'cure-dolly/95-using-word-history-the-smart-way-どうも-やっぱり-やはり.md'
      - '96. 通り and せっかく: A Metaphorical Road and an Untranslatable Word': 'cure-dolly/96-通り-and-せっかく-a-metaphorical-road-and-an-untranslatable-word.md'
      - '97. The Meanings of うち: Home, Self, Social Boundary, Time Marker - いまのうち, そのうち': 'cure-dolly/97-the-meanings-of-うち-home-self-social-boundary-time-marker-いまのうち-そのうち.md'
  - Grammar Reference:
    - Cara Pakai: g_ref/cara_pakai.md
    - Daftar Isi: g_ref/daftar_isi.md

  - Pitch Accent:
    - 'What is Pitch Accent': 'pitch/pitch_accent.md'
    - 'Basic Pitch Accent': 'pitch/pitch_basic.md'
    - 'Pitch Accent For Adjectives': 'pitch/pitch_adjective.md'
    - 'Pitch Accent For Verbs': 'pitch/pitch_verbs.md'
    - 'Pitch Accent For Nouns': 'pitch/pitch_nouns.md'
    - 'Pitch Accent For Suffix': 'pitch/pitch_suffix.md'



  



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/x-twitter
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/facebook
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/instagram
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/youtube
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx      
copyright: Copyright &copy; 2024 NaSena 21



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables        

extra_javascript:
  - javascripts/extra.js