site_name: Nasena 21
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 'index.md'
  - 'Guides':
    - 'Pendahuluan': 'pendahuluan.md'
    - 'Main Guide': 'main_guide.md'
    - 'Kanji': 'kanji.md'  
    - 'Speaking': 'speaking.md'
  - 'Mining':  
    - 'Anki': 'anki.md'
    - 'Yomitan': 'yomitan.md'
  - 'Recommendations':
    - 'Recommendations': 'recommendations.md'
  - 'Immersion':
    - 'Anime': 'anime.md'
    - 'Light Novel': 'light_novel.md'
    - 'Visual Novel': 'visual_novel.md'
  - 'Resources':
    - 'Resources': 'resources.md'
  - 'Grammar':
    - 'Grammar': 'grammar/grammar.md' 
  - 'Pitch Accent':
    - 'What is Pitch Accent': 'pitch/pitch_accent.md'
    - 'Basic Pitch Accnet': 'pitch/pitch_basic.md'
    - 'Pitch Accent For Adjectives': 'pitch/pitch_adjective.md'
    - 'Pitch Accent For Verbs': 'pitch/pitch_verbs.md'
    - 'Pitch Accnt For Nouns': 'pitch/pitch_nouns.md'

theme:
  name: material

  language: id

  font:
    text: Noto Sans Japanese
    code: Noto Serif Japanese

  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: blue 
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - tabs
    - instant
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    # - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlighting
    - search.share
    - meta
    - admonition
    - attr_list
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.superfences

  logo: kobo.jpg

  favicon: kobo.jpg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/x-twitter
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/facebook
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/instagram
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx
    - icon: fontawesome/brands/youtube
      link: https://youtu.be/dQw4w9WgXcQ?si=hQbmjAm_gtvbX8Fx      
copyright: Copyright &copy; 2024 NaSena 21

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/extra.js